server:
  port: 18781
  servlet:
    context-path: /northstarsharing
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 939129872960-b91osbhhj6glusieieaqvkhd77np0c5p.apps.googleusercontent.com
  datasource:
    url: jdbc:derby:northstarsharing_db;create=true;collation=TERRITORY_BASED:PRIMARY
  jpa:
    database-platform: org.hibernate.dialect.DerbyTenSevenDialect
    hibernate:
      ddl-auto: update
    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: ddl.sql
